### ISSUE TITLE
handling more than one binary in a single package

### ISSUE THREAD

**Issue by bacongobbler** [fishworks/fish#27]
Homebrew has a way of defining "resources" in a formula. e.g. https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb#L34-L47

There's also a way to link multiple binaries from a given package into /usr/local/bin e.g. https://github.com/Homebrew/homebrew-core/blob/master/Formula/python.rb#L196-L203

fish should have a way to allow a single fish food to install multiple packages.

**Comment by bacongobbler** [comment]
implemented in https://github.com/fishworks/fish/commit/e819c9e3a27d4d29cf6c9bfb97ad1703908bd88a

**Comment by notlmn** [comment]
Hey one quick question, you're handling archives with multiple binaries, what would be the best way to handle archives with multiple files?

For example the [Chromium archive](https://download-chromium.appspot.com/) contains not only `exe` files but other `dll`s and directories too. And all of these files are inside another directory.

When gofish is instructed to install chromium it only creates empty `chrome-win32` in the barrel, no extraction.
