### ISSUE TITLE
error installation linux

### ISSUE THREAD

**Issue by renatoassis** [fishworks/fish#42]
# Environment
OS: Arch Linux 
Kernel: x86_64 Linux 4.15.13-1-ARCH
![screenshot at 2018-04-10 22-05-54](https://user-images.githubusercontent.com/1714391/38591194-e9465886-3d0b-11e8-988e-e2f6b3736e27.png)

**Comment by renatoassis** [comment]
https://github.com/fishworks/fish/pull/43

**Comment by bacongobbler** [comment]
fixed via https://github.com/fishworks/fish/commit/0ed10fbfabe036bbec90c5dd9c61c655ee49ec2d
