### ISSUE TITLE
`vim $(gofish create foo)` did not do what I thought it would

### ISSUE THREAD

**Issue by technosophos** [fishworks/fish#49]
Platform: macOS

The manual suggests:

```
Create the Fish Food

gofish update # make sure we've got a fresh checkout of master
vim $(gofish create foo)
```

I expected this to create Food/foo.lua and open my editor to that file. Instead, it created `Food/foo` and opened my editor to a blank file (not `Food/foo`).

Workaround: I renamed `foo` to `foo.lua` and edited that.

**Comment by bacongobbler** [comment]
This was a relatively recent change avaiable in the canary releases but not in 0.2.0. Did you use the install script to install gofish or build from source? :)

I wanted to hold off on an 0.3.0 until I got a few more things like `gofish search` knocked down, but I can cut an 0.3.0 if getting a working `gofish create` would be useful for creating new food.

**Comment by bacongobbler** [comment]
Heres the issue in particular: https://github.com/fishworks/fish/issues/36

Ehh, I think I'll cut an 0.3. this along with `gofish tank` are pretty useful for creating new packages.

**Comment by technosophos** [comment]
Oh! Okay. I just curl-bashed it.

**Comment by bacongobbler** [comment]
🐠 https://github.com/fishworks/fish/releases/tag/v0.3.0 🐠
